apiVersion: v1
kind: Secret
metadata:
  name: express-secret
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: a216d2F5ODdhYQ==
  mongo-db-name: Y3J1ZF91c2Vy
  mongo-db-url: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNw==
  access-token-secret: a216d2F5ODdhYQ==
  refresh-token-secret: eWVhbXBsb3d3
